CREATE TABLE IF NOT EXISTS "USERS" (
CREATE TABLE IF NOT EXISTS "USERS" (
    "USER_ID"	INTEGER NOT NULL UNIQUE,
    "USERNAME"	varchar(100) NOT NULL,
    "BALANCE"	INTEGER NOT NULL DEFAULT 0,
    "CURRENT_SKIN"	INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY("USER_ID" AUTOINCREMENT),
    FOREIGN KEY("CURRENT_SKIN") REFERENCES "ITEMS"("ITEM_ID")
    "CURRENT_SKIN"	INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY("USER_ID" AUTOINCREMENT),
    FOREIGN KEY("CURRENT_SKIN") REFERENCES "ITEMS"("ITEM_ID")
);

CREATE TABLE IF NOT EXISTS "ITEMS" (
    "TYPE"	INTEGER NOT NULL,
CREATE TABLE IF NOT EXISTS "ITEMS" (
    "TYPE"	INTEGER NOT NULL,
    "ITEM_ID"	INTEGER NOT NULL UNIQUE,
    "ITEM_NAME"	TEXT NOT NULL,
    "COST"	INTEGER NOT NULL,
    "PATH"	TEXT NOT NULL,
    "PATH"	TEXT NOT NULL,
    PRIMARY KEY("ITEM_ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "WARDROBE" (
CREATE TABLE IF NOT EXISTS "WARDROBE" (
    "USER_ID"	INTEGER NOT NULL UNIQUE,
    "ITEMS_ID"	TEXT NOT NULL,
    FOREIGN KEY("USER_ID") REFERENCES "USERS"("USER_ID")
);

CREATE TABLE IF NOT EXISTS "LEVELS" (
CREATE TABLE IF NOT EXISTS "LEVELS" (
    "USER_ID"	INTEGER NOT NULL,
    "LVL_NUM"	INTEGER NOT NULL,
    "STATUS"	INTEGER NOT NULL DEFAULT 0,
    "BEST_TIME"	NUMERIC,
    "BEST_CASH"	INTEGER,
    FOREIGN KEY("USER_ID") REFERENCES "USERS"("USER_ID")
);

INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Ivan Kalinin', 0, '../assets/images/ivankalinin.png');
INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Mr. Khrabroff', 0, '../assets/images/khrabrov.png');
INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Mr. Antipoff', 0, '../assets/images/antipov.png');
INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Anna Gladkaya', 0, '../assets/images/annaglad.png');
INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Egor', 0, '../assets/images/egor_with_headphones.png');
INSERT INTO "ITEMS" ("TYPE", "ITEM_NAME", "COST", "PATH") VALUES (0, 'Sergey Kopel Kopeliovich', 0, '../assets/images/kopel.png');